spring:
  application:
    name: coincoin

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        ddl-auto: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coin?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234

candle-collector:
  host: localhost
  port: 8081
  url: http://${candle-collector.host}:${candle-collector.port}

logging:
  config: classpath:logback-local.xml

slack:
  token: ${SLACK_WEBHOOK_TOKEN}

binance:
  api-key: ${BINANCE_API_KEY}
  secret-key: ${BINANCE_SECRET_KEY}
